import 'tailwindcss/tailwind.css';
import Footer from '../components/Footer';
import PlayingSong from '../components/PlayingSong';
import Header from '../components/Header';
import { Providers } from './providers';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className="container bg-gray-100 dark:bg-gray-900">
        <Providers>
          <Header />
          {children}
          <PlayingSong />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
