import 'tailwindcss/tailwind.css';
import Footer from '../components/Footer';
import PlayingSong from '../components/PlayingSong';
import Header from '../components/Header';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container bg-gray-50 dark:bg-gray-900">
        <Header />
        {children}
        <PlayingSong />
        <Footer />
      </body>
    </html>
  );
}
