import React from 'react';
import 'tailwindcss/tailwind.css';
import Footer from '../components/Footer';
import PlayingSong from '../components/PlayingSong';
import Header from '../components/Header';
import { Providers } from './providers';
import { Inter, Lora } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
});

const lora = Lora({
  subsets: ['latin'],
  variable: '--font-lora',
  display: 'swap'
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

export default function RootLayout({ children }) {
  return (
    <html
      suppressHydrationWarning
      className={`${inter.variable} ${lora.variable}`}
    >
      <body className="container bg-gray-100 dark:bg-gray-900">
        <Providers>
          <Header />
          {children}
          <PlayingSong />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
